// src/views/McpView.vue
<script setup lang="ts">
import { h, onMounted, ref, watch } from "vue";
import { NButton, NEmpty, useDialog, useMessage } from "naive-ui";
import AppSwitch from "../components/AppSwitch.vue";
import TrashIcon from "../components/TrashIcon.vue";
import McpIcon from "../components/McpIcon.vue";
import McpSyncDialog from "../components/McpSyncDialog.vue";
import { api } from "../api";
import type { McpServerSpec, McpSyncPreview } from "../types";
import { mcpTransportText } from "../utils";
import {
  PhArrowsDownUp,
  PhCircleDashed,
  PhGlobe,
  PhPlus,
  PhTerminalWindow,
} from "@phosphor-icons/vue";

import McpEdit from "../components/McpEdit.vue";

const props = defineProps<{ navReset: number }>();

const message = useMessage();
const dialog = useDialog();
const servers = ref<McpServerSpec[]>([]);
const loadError = ref("");
const loaded = ref(false);
const editingServer = ref<McpServerSpec | null>(null);
const creatingServer = ref(false);
const togglingName = ref("");
// 同步差异预览：数据库 MCP 配置与 config.toml 不一致时横幅提示，弹窗内按方向选择覆盖目标
const syncPreview = ref<McpSyncPreview | null>(null);
const previewError = ref("");
const syncDialogOpen = ref(false);
const applying = ref(false);

watch(
  () => props.navReset,
  () => {
    editingServer.value = null;
    creatingServer.value = false;
  },
);

async function refresh() {
  try {
    servers.value = await api.listMcpServers();
    loadError.value = "";
  } catch (error) {
    loadError.value = String(error);
  } finally {
    loaded.value = true;
  }
  void loadPreview();
}

async function loadPreview() {
  try {
    syncPreview.value = await api.mcpSyncPreview();
    previewError.value = "";
  } catch (error) {
    // live 无法解析等场景：弹窗进入“仅可从数据库恢复”降级模式
    previewError.value = String(error);
    syncPreview.value = null;
  }
}

// 视图不再被 KeepAlive 缓存：每次切换都会重挂载，onMounted 即覆盖"返回时刷新"
onMounted(refresh);

type Transport = "http" | "stdio" | "unknown";

function transportOf(server: McpServerSpec): Transport {
  if (server.url) return "http";
  if (server.command) return "stdio";
  return "unknown";
}

function transportIconOf(server: McpServerSpec) {
  const map: Record<Transport, typeof PhGlobe> = {
    http: PhGlobe,
    stdio: PhTerminalWindow,
    unknown: PhCircleDashed,
  };
  return map[transportOf(server)];
}

function metaOf(server: McpServerSpec): string {
  if (server.command) return [server.command, ...server.args.slice(0, 2)].join(" ");
  return server.url ?? "";
}

function closeEdit() {
  editingServer.value = null;
  // 编辑页可能读取过外部修改后的 live 配置，返回列表时重新拉取
  void refresh();
}

// 行内启停开关：乐观更新，失败回滚（enabled: null = 键不存在 = Codex 默认启用）
async function toggleEnabled(server: McpServerSpec, enabled: boolean) {
  if (togglingName.value) return;
  togglingName.value = server.name;
  const previous = server.enabled;
  server.enabled = enabled ? null : false;
  try {
    await api.saveMcpServer(server.name, { ...server, enabled: enabled ? null : false });
  } catch (error) {
    server.enabled = previous;
    message.error(String(error));
  } finally {
    togglingName.value = "";
  }
}

function removeServer(server: McpServerSpec) {
  dialog.error({
    title: "删除 MCP 服务器",
    content: () =>
      h("span", [
        "确定删除“",
        h("strong", { class: "font-semibold" }, server.name),
        "”吗？~/.codex/config.toml 中对应的配置段将被移除。",
      ]),
    positiveText: "删除",
    negativeText: "取消",
    class: "delete-profile-dialog",
    icon: () => h(TrashIcon),
    positiveButtonProps: { type: "error" },
    onPositiveClick: async () => {
      try {
        await api.deleteMcpServer(server.name);
        message.success("MCP 服务器已删除");
        void refresh();
      } catch (error) {
        message.error(String(error));
      }
    },
  });
}

// 双向同步入口：先看差异再选方向；两个 header 按钮与差异横幅共用
function openSyncDialog() {
  if (applying.value) return;
  if (previewError.value) {
    syncDialogOpen.value = true;
    return;
  }
  if (syncPreview.value && syncPreview.value.entries.length === 0) {
    message.info("数据库中的 MCP 配置与 config.toml 一致，无需处理");
    return;
  }
  syncDialogOpen.value = true;
}

async function onApply(direction: "live-to-db" | "db-to-live") {
  if (applying.value) return;
  applying.value = true;
  try {
    if (direction === "live-to-db") {
      const count = await api.importMcpFromLive();
      message.success(`已用 config.toml 覆盖数据库中的 MCP 配置，共 ${count} 台服务器`);
    } else {
      const count = await api.restoreMcpFromDatabase();
      message.success(`已用数据库中的 MCP 配置覆盖 config.toml，共 ${count} 台服务器`);
    }
    syncDialogOpen.value = false;
    await refresh();
  } catch (error) {
    // 失败保留弹窗，用户可重试或取消
    message.error(String(error));
  } finally {
    applying.value = false;
  }
}
</script>

<template>
  <McpEdit v-if="editingServer" :server="editingServer" @back="closeEdit" />
  <McpEdit v-else-if="creatingServer" :server="null" create @back="creatingServer = false" />
  <section v-else class="apple-scroll-page mx-auto w-full max-w-none">
    <header class="apple-page-bar flex-wrap justify-between gap-4">
      <div class="flex min-w-0 items-center gap-2.5">
        <span class="settings-icon-tile grid h-9 w-9 shrink-0 place-items-center rounded-[10px] text-accent">
          <McpIcon class="h-[22px] w-[22px]" />
        </span>
        <div class="min-w-0">
          <div class="flex items-center gap-2">
            <div class="apple-title">MCP 服务器管理</div>
            <span v-if="loaded" class="apple-chip" :aria-label="servers.length + ' 台服务器'">{{ servers.length }}</span>
          </div>
        </div>
      </div>
      <div class="flex flex-wrap items-center gap-2">
        <n-button secondary :disabled="applying" @click="openSyncDialog">
          <template #icon>
            <PhArrowsDownUp class="h-4 w-4" weight="bold" aria-hidden="true" />
          </template>
          处理配置差异
        </n-button>
        <n-button type="primary" @click="creatingServer = true">
          <template #icon>
            <PhPlus class="h-4 w-4" weight="bold" aria-hidden="true" />
          </template>
          添加服务器
        </n-button>
      </div>
    </header>

    <div class="apple-edit-content">
    <p v-if="loadError" class="muted mt-4 text-sm">
      {{ loadError }}<span v-if="loaded">config.toml 无法解析时，可点「处理配置差异」用数据库中的 MCP 配置恢复。</span>
    </p>

    <div class="mt-[var(--gap-page)]">
      <!-- 数据库 MCP 配置与 config.toml 有差异时提示；两侧数量不一致也要显示，避免空列表误导 -->
      <div v-if="syncPreview && syncPreview.entries.length" class="apple-list-row mb-2">
        <span class="flex min-w-0 items-center gap-2">
          <span class="apple-chip chip-warn">MCP 差异</span>
          <span class="muted truncate text-sm">
            数据库与 config.toml 有 {{ syncPreview.entries.length }} 项 MCP 配置不同
          </span>
        </span>
        <button type="button" class="apple-inline-btn" @click="openSyncDialog">查看并处理</button>
      </div>
      <n-empty
        v-if="loaded && servers.length === 0"
        description="还没有 MCP 服务器。点击“添加服务器”把第一个 MCP 服务写进 config.toml。"
        class="apple-group py-14"
      />
      <div v-else-if="servers.length" class="space-y-2">
        <div
          v-for="server in servers"
          :key="server.name"
          class="apple-list-row"
        >
          <button
            type="button"
            class="group flex min-w-0 cursor-pointer items-center gap-2.5 text-left"
            :aria-label="`编辑 ${server.name}`"
            title="点击编辑"
            @click="editingServer = server"
          >
            <span class="settings-icon-tile grid h-8 w-8 shrink-0 place-items-center rounded-lg text-accent transition-colors group-hover:bg-[var(--selection-bg)]">
              <component :is="transportIconOf(server)" class="h-4 w-4" weight="bold" aria-hidden="true" />
            </span>
            <div class="min-w-0">
              <div class="flex items-center gap-2">
                <span class="min-w-0 truncate text-[var(--font-size-base)] font-semibold transition-colors group-hover:text-accent">
                  {{ server.name }}
                </span>
                <span class="shrink-0 rounded-md bg-black/5 px-1.5 py-px text-[10px] font-medium tracking-wide text-zinc-500 dark:bg-white/10 dark:text-zinc-400">
                  {{ mcpTransportText(server) }}
                </span>
              </div>
              <div class="mono muted truncate text-[11px]">{{ metaOf(server) }}</div>
            </div>
          </button>
          <div class="flex shrink-0 items-center gap-1.5">
            <AppSwitch
              size="small"
              :value="server.enabled !== false"
              :aria-label="`启用 ${server.name}`"
              @update:value="toggleEnabled(server, $event)"
            />
            <button
              type="button"
              class="apple-icon-button text-[var(--danger)]/70 hover:bg-[var(--danger)]/10 hover:text-[var(--danger)]"
              title="删除"
              :aria-label="'删除 ' + server.name"
              @click="removeServer(server)"
            >
              <TrashIcon />
            </button>
          </div>
        </div>
      </div>
    </div>

    </div>

    <McpSyncDialog
      :show="syncDialogOpen"
      :preview="syncPreview"
      :preview-error="previewError"
      :busy="applying"
      @update:show="syncDialogOpen = $event"
      @apply="onApply"
    />
  </section>
</template>

// src/features/mcp/McpView.tsx
import { ArrowDownUp, CircleDashed, Globe, Plus, Terminal } from "lucide-react";
import { useEffect, useState } from "react";
import { api } from "../../api";
import { useFeedback } from "../../app/Feedback";
import { getCachedMcpServers, loadMcpServers, setMcpServersCache } from "../../app/managementDataCache";
import { AppSwitch } from "../../components/AppSwitch";
import { EmptyStateCard } from "../../components/EmptyStateCard";
import { McpIcon } from "../../components/McpIcon";
import { TrashIcon } from "../../components/TrashIcon";
import { mcpTransportText } from "../../utils";
import type { McpServerSpec, McpSyncPreview } from "../../types";
import McpEdit from "./McpEdit";
import McpSyncDialog from "./McpSyncDialog";

type SyncDirection = "live-to-db" | "db-to-live";
type Transport = "http" | "stdio" | "unknown";

export default function McpView() {
  const feedback = useFeedback();
  const cachedServers = getCachedMcpServers();
  const [servers, setServers] = useState<McpServerSpec[]>(() => cachedServers ?? []);
  const [loaded, setLoaded] = useState(cachedServers !== null);
  const [loadError, setLoadError] = useState("");
  const [editingServer, setEditingServer] = useState<McpServerSpec | null>(null);
  const [creatingServer, setCreatingServer] = useState(false);
  const [togglingName, setTogglingName] = useState("");
  const [syncPreview, setSyncPreview] = useState<McpSyncPreview | null>(null);
  const [previewError, setPreviewError] = useState("");
  const [syncOpen, setSyncOpen] = useState(false);
  const [applying, setApplying] = useState(false);

  const loadPreview = async () => {
    try { setSyncPreview(await api.mcpSyncPreview()); setPreviewError(""); }
    catch (error) { setPreviewError(String(error)); setSyncPreview(null); }
  };
  const refresh = async (force = false) => {
    try { setServers(await loadMcpServers(force)); setLoadError(""); }
    catch (error) { setLoadError(String(error)); }
    finally { setLoaded(true); }
    await loadPreview();
  };
  useEffect(() => { void refresh(); }, []);

  const transportOf = (server: McpServerSpec): Transport => server.url ? "http" : server.command ? "stdio" : "unknown";
  const transportIcon = (server: McpServerSpec) => { const current = transportOf(server); return current === "http" ? Globe : current === "stdio" ? Terminal : CircleDashed; };
  const metaOf = (server: McpServerSpec) => server.command ? [server.command, ...server.args.slice(0, 2)].join(" ") : server.url ?? "";

  const toggleEnabled = async (server: McpServerSpec, enabled: boolean) => {
    if (togglingName) return;
    setTogglingName(server.name);
    const previous = server.enabled;
    setServers((current) => {
      const next = current.map((item) => item.name === server.name ? { ...item, enabled: enabled ? null : false } : item);
      setMcpServersCache(next);
      return next;
    });
    try { await api.saveMcpServer(server.name, { ...server, enabled: enabled ? null : false }); }
    catch (error) { setServers((current) => { const next = current.map((item) => item.name === server.name ? { ...item, enabled: previous } : item); setMcpServersCache(next); return next; }); feedback.error(String(error)); }
    finally { setTogglingName(""); }
  };

  const removeServer = async (server: McpServerSpec) => {
    const confirmed = await feedback.confirm({ title: "删除 MCP 服务器", description: <>确定删除“<strong>{server.name}</strong>”吗？~/.codex/config.toml 中对应的配置段将被移除。</>, confirmText: "删除", destructive: true });
    if (!confirmed) return;
    try { await api.deleteMcpServer(server.name); feedback.success("MCP 服务器已删除"); await refresh(true); }
    catch (error) { feedback.error(String(error)); }
  };

  const openSyncDialog = () => {
    if (applying) return;
    if (previewError) { setSyncOpen(true); return; }
    if (syncPreview && syncPreview.entries.length === 0) { feedback.info("数据库中的 MCP 配置与 config.toml 一致，无需处理"); return; }
    setSyncOpen(true);
  };
  const onApply = async (direction: SyncDirection) => {
    if (applying) return;
    setApplying(true);
    try {
      if (direction === "live-to-db") { const count = await api.importMcpFromLive(); feedback.success(`已用 config.toml 覆盖数据库中的 MCP 配置，共 ${count} 台服务器`); }
      else { const count = await api.restoreMcpFromDatabase(); feedback.success(`已用数据库中的 MCP 配置覆盖 config.toml，共 ${count} 台服务器`); }
      setSyncOpen(false);
      await refresh(true);
    } catch (error) { feedback.error(String(error)); }
    finally { setApplying(false); }
  };

  if (editingServer || creatingServer) return <McpEdit server={editingServer} create={creatingServer} onBack={() => { setEditingServer(null); setCreatingServer(false); void refresh(true); }} />;
  return <section className="apple-scroll-page mx-auto w-full max-w-none"><header className="apple-page-bar flex-wrap justify-between gap-4"><div className="flex min-w-0 items-center gap-2.5"><span className="settings-icon-tile grid h-9 w-9 shrink-0 place-items-center rounded-[10px] text-accent"><McpIcon className="h-[22px] w-[22px]" /></span><div className="flex items-center gap-2"><div className="apple-title">MCP 服务器管理</div>{loaded ? <span className="apple-chip" aria-label={`${servers.length} 台服务器`}>{servers.length}</span> : null}</div></div><div className="flex w-full max-w-md items-center justify-end gap-2"><button type="button" className="apple-action-button" disabled={applying} onClick={openSyncDialog}><ArrowDownUp className="h-4 w-4" strokeWidth={2} />处理配置差异</button><button type="button" className="apple-action-button app-button--primary" onClick={() => setCreatingServer(true)}><Plus className="h-4 w-4" strokeWidth={2} />添加服务器</button></div></header><div className="apple-edit-content">{loadError ? <p className="muted mt-4 text-sm">{loadError}{loaded ? "config.toml 无法解析时，可点「处理配置差异」用数据库中的 MCP 配置恢复。" : ""}</p> : null}<div>{syncPreview && syncPreview.entries.length ? <div className="apple-list-row mb-2"><span className="flex min-w-0 items-center gap-2"><span className="apple-chip chip-warn">MCP 差异</span><span className="muted truncate text-sm">数据库与 config.toml 有 {syncPreview.entries.length} 项 MCP 配置不同</span></span><button type="button" className="apple-inline-btn" onClick={openSyncDialog}>查看并处理</button></div> : null}{!servers.length ? <EmptyStateCard loading={!loaded} icon={<McpIcon className="h-5 w-5" />}><p className="muted">还没有 MCP 服务器。点击“添加服务器”把第一个 MCP 服务写进 config.toml。</p></EmptyStateCard> : servers.length ? <div className="space-y-2">{servers.map((server) => { const Icon = transportIcon(server); return <div key={server.name} className="apple-list-row"><button type="button" className="group flex min-w-0 cursor-pointer items-center gap-2.5 text-left" aria-label={`编辑 ${server.name}`} title="点击编辑" onClick={() => setEditingServer(server)}><span className="settings-icon-tile grid h-8 w-8 shrink-0 place-items-center rounded-lg text-accent transition-colors group-hover:bg-(--selection-bg)"><Icon className="h-4 w-4" strokeWidth={2} /></span><div className="min-w-0"><div className="flex items-center gap-2"><span className="min-w-0 truncate font-semibold transition-colors group-hover:text-accent">{server.name}</span><span className="shrink-0 rounded-md bg-black/5 px-1.5 py-px text-[10px] font-medium tracking-wide muted dark:bg-white/10">{mcpTransportText(server)}</span></div><div className="mono muted meta-xs truncate">{metaOf(server)}</div></div></button><div className="flex shrink-0 items-center gap-1.5"><AppSwitch size="sm" checked={server.enabled !== false} label={`启用 ${server.name}`} onCheckedChange={(value) => void toggleEnabled(server, value)} /><button type="button" className="apple-icon-button text-[var(--danger)]/70 hover:bg-(--danger)/10 hover:text-[var(--danger)]" title="删除" aria-label={`删除 ${server.name}`} onClick={() => void removeServer(server)}><TrashIcon /></button></div></div>; })}</div> : null}</div></div><McpSyncDialog open={syncOpen} preview={syncPreview} previewError={previewError} busy={applying} onClose={() => setSyncOpen(false)} onApply={(direction) => void onApply(direction)} /></section>;
}
