// src/views/ProfilesView.vue
<script setup lang="ts">
import { computed, defineAsyncComponent, h, onBeforeUnmount, onMounted, ref, watch } from "vue";
import {
  NButton,
  NEmpty,
  NInput,
  NModal,
  NProgress,
  NTag,
  useDialog,
  useMessage,
} from "naive-ui";
import ProfileCard from "../components/ProfileCard.vue";
import TrashIcon from "../components/TrashIcon.vue";
import draggable from "vuedraggable";
import { api } from "../api";
import type { AppState, ManagedAccount, ProfileSummary, RestartStage } from "../types";
import { PhArrowClockwise, PhCamera, PhPlus } from "@phosphor-icons/vue";

// 编辑页按需加载：只在打开编辑/新建时拉取，避免把 CodeMirror/预设数据带进启动入口
const ProfileEdit = defineAsyncComponent(() => import("../components/ProfileEdit.vue"));

const props = defineProps<{ state: AppState }>();
const emit = defineEmits<{ refresh: [] }>();

const message = useMessage();
const dialog = useDialog();
const busy = ref(false);
const restartStage = ref<RestartStage>("idle");
const restartMessage = ref("");
const modalVisible = ref(false);
const modalMode = ref<"capture" | "rename">("capture");
const profileName = ref("");
const editingProfile = ref<ProfileSummary | null>(null);
const creatingProfile = ref(false);
const modalProfile = ref<ProfileSummary | null>(null);
const subscriptionAuthed = ref(false);
const subscriptionAccount = ref<string | null>(null);
// 手动排序：vuedraggable（SortableJS）实时重排，结束后持久化
function onDragStart() {
  document.body.classList.add("drag-active");
}

async function persistOrder() {
  try {
    await api.reorderProfiles(props.state.profiles.map((item) => item.id));
  } catch (error) {
    message.error(String(error));
    emit("refresh");
  } finally {
    document.body.classList.remove("drag-active");
  }
}
const authAccounts = ref<ManagedAccount[]>([]);

let unlisten: (() => void) | null = null;

const progress = computed(() => {
  const values: Record<RestartStage, number> = {
    idle: 0,
    stopping: 18,
    waiting: 48,
    launching: 82,
    success: 100,
    error: 100,
  };
  return values[restartStage.value];
});

const stageText = computed(() => {
  const values: Record<RestartStage, string> = {
    idle: "空闲",
    stopping: "正在停止 Codex",
    waiting: "等待进程退出",
    launching: "正在启动 Codex",
    success: "重启成功",
    error: "重启失败",
  };
  return values[restartStage.value];
});

let restartCollapseTimer: ReturnType<typeof setTimeout> | undefined;

// 重启进度卡入场/收起：rAF 驱动 + 每帧高度/外边距取整。
// 不用 CSS 高度过渡——它收尾会落到小数像素，列表在亚像素上重绘产生顿挫（实测收尾步进 3.4px→1.9px 全小数）；
// 每帧取整后列表始终落在整数像素上，收尾平滑。
// 内边距也必须一起动画：border-box 下盒子高度不能小于上下内边距之和（py-3=24px），
// 不压内边距的话高度会被浏览器钳制在 24px，移除瞬间列表再跳 24px（实测复现）。
const RESTART_CARD_DURATION = 360;

function animateRestartCard(el: Element, entering: boolean, done: () => void) {
  const node = el as HTMLElement;
  if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
    done();
    return;
  }
  const natural = node.scrollHeight;
  const margin = parseFloat(getComputedStyle(node).marginTop) || 24;
  const padTop = parseFloat(getComputedStyle(node).paddingTop) || 0;
  const padBottom = parseFloat(getComputedStyle(node).paddingBottom) || 0;
  const fromH = entering ? 0 : natural;
  const toH = entering ? natural : 0;
  const fromM = entering ? 0 : margin;
  const toM = entering ? margin : 0;
  node.style.overflow = "hidden";
  node.style.opacity = entering ? "0" : "1";
  const start = performance.now();
  const tick = (now: number) => {
    const progress = Math.min(1, (now - start) / RESTART_CARD_DURATION);
    // easeOutQuart：与全站曲线同属强 ease-out，收尾更快、尾部不留拖影
    const eased = 1 - (1 - progress) ** 4;
    node.style.height = `${Math.round(fromH + (toH - fromH) * eased)}px`;
    node.style.marginTop = `${Math.round(fromM + (toM - fromM) * eased)}px`;
    node.style.paddingTop = `${Math.round(padTop * (entering ? eased : 1 - eased))}px`;
    node.style.paddingBottom = `${Math.round(padBottom * (entering ? eased : 1 - eased))}px`;
    node.style.opacity = `${entering ? eased : 1 - eased}`;
    if (progress < 1) {
      requestAnimationFrame(tick);
      return;
    }
    // 进场结束后复位内联样式（卡片仍驻留）；出场不复位——元素随后即被移除，
    // 复位会把它弹回完整高度+外边距一帧，列表先下移再上弹，形成收尾顿挫（实测末帧跳 24px）
    if (entering) {
      node.style.cssText = "";
    }
    done();
  };
  requestAnimationFrame(tick);
}

function onRestartCardEnter(el: Element, done: () => void) {
  animateRestartCard(el, true, done);
}

function onRestartCardLeave(el: Element, done: () => void) {
  animateRestartCard(el, false, done);
}

watch(restartStage, (stage) => {
  if (restartCollapseTimer !== undefined) {
    clearTimeout(restartCollapseTimer);
    restartCollapseTimer = undefined;
  }
  if (stage === "success") {
    // 进度跑完停留片刻让用户看到“重启成功”，再自动收缩回空闲
    restartCollapseTimer = setTimeout(() => {
      restartStage.value = "idle";
      restartCollapseTimer = undefined;
    }, 1200);
  }
});

function openCapture() {
  modalMode.value = "capture";
  modalProfile.value = null;
  profileName.value = "";
  modalVisible.value = true;
}

function openRename(profile: ProfileSummary) {
  modalMode.value = "rename";
  modalProfile.value = profile;
  profileName.value = profile.name;
  modalVisible.value = true;
}

function closeEdit() {
  editingProfile.value = null;
  // 编辑页可能读取过外部修改后的 live 配置，返回列表时重新拉取状态
  emit("refresh");
}

function blurActiveOnModalLeave() {
  (document.activeElement as HTMLElement | null)?.blur?.();
}

async function submitModal() {
  if (busy.value) return;
  busy.value = true;
  try {
    if (modalMode.value === "capture") {
      await api.captureProfile(profileName.value);
      message.success("已捕获并设为使用中");
    } else if (modalProfile.value) {
      await api.renameProfile(modalProfile.value.id, profileName.value);
      message.success("供应商已重命名");
    }
    modalVisible.value = false;
    emit("refresh");
  } catch (error) {
    message.error(String(error));
  } finally {
    busy.value = false;
  }
}

async function applyProfile(profile: ProfileSummary) {
  if (busy.value) return;
  busy.value = true;
  try {
    await api.applyProfile(profile.id);
    message.success("模型配置已应用");
    if (props.state.settings.auto_restart) {
      await restart(true);
    }
    emit("refresh");
  } catch (error) {
    message.error(String(error));
  } finally {
    busy.value = false;
  }
}

async function removeProfile(profile: ProfileSummary) {
  dialog.error({
    title: "删除供应商",
    content: `确定删除“${profile.name}”吗？删除后不可恢复。`,
    positiveText: "删除",
    negativeText: "取消",
    class: "delete-profile-dialog",
    icon: () => h(TrashIcon),
    positiveButtonProps: { type: "error" },
    onPositiveClick: async () => {
      try {
        await api.deleteProfile(profile.id);
        message.success("供应商已删除");
        emit("refresh");
      } catch (error) {
        message.error(String(error));
      }
    },
  });
}

async function duplicateProfile(profile: ProfileSummary) {
  if (busy.value) return;
  busy.value = true;
  try {
    const copy = await api.duplicateProfile(profile.id);
    message.success(`已复制为「${copy.name}」`);
    emit("refresh");
  } catch (error) {
    message.error(String(error));
  } finally {
    busy.value = false;
  }
}

async function restart(force = false) {
  if (busy.value && !force) return;
  busy.value = true;
  restartStage.value = "stopping";
  restartMessage.value = "";
  try {
    await api.restartCodex();
    message.success("Codex 已重启");
    emit("refresh");
  } catch (error) {
    restartMessage.value = String(error);
    message.error(String(error));
  } finally {
    busy.value = false;
  }
}

onMounted(async () => {
  unlisten = await api.onRestartProgress((payload) => {
    restartStage.value = payload.stage;
    restartMessage.value = payload.message ?? "";
  });
  try {
    const status = await api.authGetStatus();
    subscriptionAuthed.value = status.authenticated;
    authAccounts.value = status.accounts;
    subscriptionAccount.value =
      status.accounts.find((account) => account.id === status.default_account_id)?.login ??
      status.external?.login ??
      null;
  } catch {
    subscriptionAuthed.value = false;
  }
});

function boundAccountLogin(profile: ProfileSummary): string | null {
  return (
    authAccounts.value.find((account) => account.id === profile.account_id)?.login ?? null
  );
}

onBeforeUnmount(() => {
  unlisten?.();
  if (restartCollapseTimer !== undefined) clearTimeout(restartCollapseTimer);
});
</script>

<template>
  <ProfileEdit
    v-if="editingProfile"
    :profile="editingProfile"
    @back="closeEdit"
    @changed="emit('refresh')"
  />
  <ProfileEdit
    v-else-if="creatingProfile"
    :profile="null"
    create
    @back="creatingProfile = false"
    @changed="emit('refresh')"
  />
  <section v-else class="mx-auto w-full max-w-none">
    <header class="flex flex-wrap items-center justify-between gap-4 pb-2">
      <div class="flex min-w-0 flex-wrap items-center gap-x-4 gap-y-2 text-sm">
        <span class="inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium transition-colors" :class="state.codex.running ? 'border-success/25 bg-success/10 text-[#248a3d] dark:border-success/30 dark:bg-success/10 dark:text-[#6ee7a0]' : 'border-[var(--panel-border)] bg-black/4 text-zinc-500 dark:bg-white/6'">
          <span class="relative flex h-2 w-2">
            <span v-if="state.codex.running" class="absolute inline-flex h-full w-full animate-ping rounded-full bg-success opacity-50" />
            <span class="relative inline-flex h-2 w-2 rounded-full shadow-[0_0_6px_1px_rgba(52,199,89,0.45)]" :class="state.codex.running ? 'bg-success' : 'bg-zinc-400 shadow-none'" />
          </span>
          Codex {{ state.codex.running ? "运行中" : "未运行" }}
        </span>
      </div>
      <div class="flex flex-wrap items-center gap-2">
        <n-button quaternary :disabled="busy" :loading="restartStage !== 'idle' && restartStage !== 'success' && restartStage !== 'error'" title="重启 Codex" @click="restart(false)">
          <template #icon>
            <PhArrowClockwise class="h-4 w-4" weight="bold" aria-hidden="true" />
          </template>
          重启 Codex
        </n-button>
        <n-button quaternary :disabled="busy" title="捕获当前配置" aria-label="捕获当前配置" @click="openCapture">
          <template #icon>
            <PhCamera class="h-4 w-4" weight="bold" aria-hidden="true" />
          </template>
        </n-button>
        <n-button type="primary" :disabled="busy" @click="creatingProfile = true">
          <template #icon>
            <PhPlus class="h-4 w-4" weight="bold" aria-hidden="true" />
          </template>
          添加供应商
        </n-button>
      </div>
    </header>

    <transition :css="false" @enter="onRestartCardEnter" @leave="onRestartCardLeave">
      <div v-if="restartStage !== 'idle'" class="apple-group mt-[var(--gap-page)] px-4 py-3">
        <div class="flex items-center justify-between gap-3">
          <div class="font-semibold">重启进度</div>
          <n-tag size="small" :type="restartStage === 'error' ? 'error' : restartStage === 'success' ? 'success' : 'default'">
            {{ stageText }}
          </n-tag>
        </div>
        <n-progress class="mt-3" type="line" :percentage="progress" :status="restartStage === 'error' ? 'error' : restartStage === 'success' ? 'success' : 'default'" :show-indicator="false" />
        <p v-if="restartMessage" class="muted mt-3 text-sm">{{ restartMessage }}</p>
      </div>
    </transition>

    <div class="mt-[var(--gap-page)]">
      <n-empty v-if="state.profiles.length === 0" description="还没有供应商配置。可以添加内置官方供应商，或先把 ~/.codex/config.toml 调整到目标状态，再点击“捕获当前配置”。" class="apple-group py-14" />
      <template v-else>
        <draggable
          tag="div"
          class="apple-group relative will-change-transform"
          :component-data="{ name: 'profile-list' }"
          :list="state.profiles"
          item-key="id"
          handle=".drag-handle"
          :animation="250"
          :force-fallback="true"
          fallback-on-body="true"
          :fallback-tolerance="5"
          ghost-class="drag-ghost"
          drag-class="drag-dragging"
          @start="onDragStart"
          @end="persistOrder"
        >
          <template #item="{ element: profile, index }">
            <ProfileCard
              :class="index === 0 ? '' : 'profile-card-divider'"
              :profile="profile"
              :active="profile.id === state.active_profile_id"
              :busy="busy"
              :subscription-authed="subscriptionAuthed"
              :subscription-account="subscriptionAccount"
              :bound-account="boundAccountLogin(profile)"
              :balance-cache="state.balance_cache"
              @apply="applyProfile(profile)"
              @rename="openRename(profile)"
              @edit="editingProfile = profile"
              @remove="removeProfile(profile)"
              @duplicate="duplicateProfile(profile)"
            />
          </template>
        </draggable>
      </template>
    </div>

    <n-modal v-model:show="modalVisible" preset="card" class="max-w-[460px]" :title="modalMode === 'capture' ? '保存当前配置快照' : '重命名供应商'" @after-leave="blurActiveOnModalLeave">
      <div class="space-y-4">
        <p class="muted text-sm">
          {{ modalMode === "capture" ? "为当前 Codex 配置创建快照，切换供应商后可一键恢复。" : "输入新的供应商名称。" }}
        </p>
        <n-input v-model:value="profileName" maxlength="50" show-count placeholder="例如：DeepSeek 日常" @keyup.enter="submitModal" />
        <div class="flex justify-end gap-2">
          <n-button @click="modalVisible = false">取消</n-button>
          <n-button type="primary" :loading="busy" @click="submitModal">保存</n-button>
        </div>
      </div>
    </n-modal>
  </section>
</template>

// src/features/profiles/ProfilesView.tsx
import { Camera, Plus, RefreshCw, Server } from "lucide-react";
import { DndContext, DragOverlay, KeyboardSensor, PointerSensor, closestCenter, useSensor, useSensors, type DragEndEvent, type DragStartEvent } from "@dnd-kit/core";
import { SortableContext, arrayMove, verticalListSortingStrategy } from "@dnd-kit/sortable";
import { useCallback, useEffect, useRef, useState } from "react";
import { api } from "../../api";
import { useFeedback } from "../../app/Feedback";
import { AppDialog } from "../../components/AppDialog";
import { EmptyStateCard } from "../../components/EmptyStateCard";
import { ProfileIconTile } from "../../components/ProfileIconTile";
import type { AppState, AuthStatus, ProfileSummary, RestartStage } from "../../types";
import ProfileCard from "./ProfileCard";
import ProfileEdit from "./ProfileEdit";

interface ProfilesViewProps {
  state: AppState;
  activationEpoch: number;
  onRefresh: () => Promise<void>;
}

const progressByStage: Record<RestartStage, number> = { idle: 0, stopping: 18, waiting: 48, launching: 82, success: 100, error: 100 };
const textByStage: Record<RestartStage, string> = { idle: "空闲", stopping: "正在停止 Codex", waiting: "等待进程退出", launching: "正在启动 Codex", success: "重启成功", error: "重启失败" };
const RESTART_CARD_DURATION = 360;

interface RestartProgressCardProps {
  stage: RestartStage;
  message: string;
  visible: boolean;
  onHidden: () => void;
}

function ProfileDragPreview({ profile, width }: { profile: ProfileSummary; width: number | null }) {
  return <div className="drag-dragging profile-drag-preview" style={{ width: width ? `${width}px` : undefined }}><div className="flex items-center gap-3 px-5 py-4.5"><ProfileIconTile name={profile.name} icon={profile.icon} /><div className="min-w-0"><div className="title-md truncate">{profile.name}</div><div className="muted mt-1 flex items-center gap-1"><span className="apple-chip">{profile.model ?? "未设置"}</span>{profile.provider ? <span className="apple-chip">{profile.provider}</span> : null}<span className="apple-chip">{profile.reasoning_effort ?? "默认"}</span></div></div></div></div>;
}

function RestartProgressCard({ stage, message, visible, onHidden }: RestartProgressCardProps) {
  const revealRef = useRef<HTMLDivElement>(null);

  // 出场：grid 收起过渡结束后卸载；transitionend 丢失时用定时器兜底
  useEffect(() => {
    if (visible) return;
    if (window.matchMedia("(prefers-reduced-motion: reduce)").matches) {
      onHidden();
      return;
    }
    const node = revealRef.current;
    if (!node) {
      onHidden();
      return;
    }
    const finish = (event?: TransitionEvent) => {
      if (event && (event.target !== node || event.propertyName !== "grid-template-rows")) return;
      onHidden();
    };
    node.addEventListener("transitionend", finish as EventListener);
    const timer = window.setTimeout(() => finish(), RESTART_CARD_DURATION + 80);
    return () => {
      node.removeEventListener("transitionend", finish as EventListener);
      window.clearTimeout(timer);
    };
  }, [visible, onHidden]);

  return <div ref={revealRef} className={`restart-card-reveal${visible ? " restart-card-reveal--open" : ""}`} aria-hidden={!visible}><div className="restart-card-reveal__inner"><div className="apple-group mb-[var(--gap-page)] px-4 py-3"><div className="flex items-center justify-between gap-3"><div className="font-semibold">重启进度</div><span className={`apple-chip ${stage === "error" ? "chip-danger" : stage === "success" ? "chip-success" : ""}`}>{textByStage[stage]}</span></div><div className="mt-3 h-2 overflow-hidden rounded-full bg-black/8 dark:bg-white/8"><div className={`h-full rounded-full transition-[width] duration-300 ${stage === "error" ? "bg-danger" : stage === "success" ? "bg-success" : "bg-accent"}`} style={{ width: `${progressByStage[stage]}%` }} /></div>{message ? <p className="muted mt-3 text-sm">{message}</p> : null}</div></div></div>;
}

export default function ProfilesView({ state, activationEpoch, onRefresh }: ProfilesViewProps) {
  const feedback = useFeedback();
  const [items, setItems] = useState(state.profiles);
  const [busy, setBusy] = useState(false);
  const [restartStage, setRestartStage] = useState<RestartStage>("idle");
  const [restartMessage, setRestartMessage] = useState("");
  const [restartCardStage, setRestartCardStage] = useState<RestartStage>("idle");
  const [restartCardMounted, setRestartCardMounted] = useState(false);
  const [restartCardVisible, setRestartCardVisible] = useState(false);
  const [editingProfile, setEditingProfile] = useState<ProfileSummary | null>(null);
  const [creatingProfile, setCreatingProfile] = useState(false);
  const [modal, setModal] = useState<"capture" | "rename" | null>(null);
  const [modalProfile, setModalProfile] = useState<ProfileSummary | null>(null);
  const [profileName, setProfileName] = useState("");
  const [draggedProfileId, setDraggedProfileId] = useState<string | null>(null);
  const [draggedProfileWidth, setDraggedProfileWidth] = useState<number | null>(null);
  const [authStatus, setAuthStatus] = useState<AuthStatus>(state.auth_status);
  const nameInput = useRef<HTMLInputElement>(null);
  const previousRestartStage = useRef<RestartStage>("idle");
  const dragHoverReleaseRef = useRef<(() => void) | null>(null);
  const duplicatingProfileRef = useRef(false);
  const sensors = useSensors(useSensor(PointerSensor, { activationConstraint: { distance: 5 } }), useSensor(KeyboardSensor));

  useEffect(() => setItems(state.profiles), [state.profiles]);
  useEffect(() => setAuthStatus(state.auth_status), [state.auth_status]);

  useEffect(() => () => {
    document.body.classList.remove("drag-active", "drag-settling");
    dragHoverReleaseRef.current?.();
  }, []);

  useEffect(() => {
    let disposed = false;
    let unlisten: (() => void) | undefined;
    void api.onRestartProgress((payload) => {
      if (!disposed) {
        setRestartStage(payload.stage);
        setRestartMessage(payload.message ?? "");
      }
    }).then((cleanup) => {
      if (disposed) cleanup();
      else unlisten = cleanup;
    });
    void api.authGetStatus().then((status) => { if (!disposed) setAuthStatus(status); }).catch(() => undefined);
    return () => { disposed = true; unlisten?.(); };
  }, []);

  useEffect(() => {
    if (restartStage !== "success") return;
    const timer = window.setTimeout(() => setRestartStage("idle"), 1200);
    return () => window.clearTimeout(timer);
  }, [restartStage]);

  useEffect(() => {
    if (restartStage === "idle") {
      if (previousRestartStage.current !== "idle") setRestartCardVisible(false);
    } else {
      setRestartCardStage(restartStage);
      setRestartCardMounted(true);
      setRestartCardVisible(true);
    }
    previousRestartStage.current = restartStage;
  }, [restartStage]);

  const onRestartCardHidden = useCallback(() => setRestartCardMounted(false), []);

  const releaseCardHoverSuppression = () => {
    const release = dragHoverReleaseRef.current;
    if (release) release();
  };

  const suppressCardHover = () => {
    releaseCardHoverSuppression();
    const activeElement = document.activeElement;
    if (activeElement instanceof HTMLElement && activeElement.classList.contains("drag-handle")) activeElement.blur();
    document.body.classList.add("drag-settling");
    const release = () => {
      document.body.classList.remove("drag-settling");
      window.removeEventListener("pointermove", release);
      if (dragHoverReleaseRef.current === release) dragHoverReleaseRef.current = null;
    };
    dragHoverReleaseRef.current = release;
    window.addEventListener("pointermove", release, { once: true });
  };

  const persistOrder = async (previous: ProfileSummary[], next: ProfileSummary[]) => {
    try {
      await api.reorderProfiles(next.map((item) => item.id));
    } catch (error) {
      setItems(previous);
      feedback.error(String(error));
      await onRefresh();
    }
  };

  const onDragEnd = (event: DragEndEvent) => {
    document.body.classList.remove("drag-active");
    suppressCardHover();
    setDraggedProfileId(null);
    setDraggedProfileWidth(null);
    const { active, over } = event;
    if (!over || active.id === over.id) return;
    const oldItems = items;
    const oldIndex = oldItems.findIndex((item) => item.id === active.id);
    const newIndex = oldItems.findIndex((item) => item.id === over.id);
    if (oldIndex < 0 || newIndex < 0) return;
    const next = arrayMove(oldItems, oldIndex, newIndex);
    setItems(next);
    void persistOrder(oldItems, next);
  };

  const onDragStart = ({ active }: DragStartEvent) => {
    releaseCardHoverSuppression();
    document.body.classList.add("drag-active");
    setDraggedProfileId(String(active.id));
    setDraggedProfileWidth(active.rect.current.initial?.width ?? null);
  };

  const onDragCancel = () => {
    document.body.classList.remove("drag-active");
    suppressCardHover();
    setDraggedProfileId(null);
    setDraggedProfileWidth(null);
  };

  const openCapture = () => { setModal("capture"); setModalProfile(null); setProfileName(""); };
  const openRename = (profile: ProfileSummary) => { setModal("rename"); setModalProfile(profile); setProfileName(profile.name); };

  const submitModal = async () => {
    if (busy || !modal) return;
    setBusy(true);
    try {
      if (modal === "capture") {
        await api.captureProfile(profileName.trim());
        feedback.success("已捕获并设为使用中");
      } else if (modalProfile) {
        await api.renameProfile(modalProfile.id, profileName.trim());
        feedback.success("供应商已重命名");
      }
      setModal(null);
      await onRefresh();
    } catch (error) { feedback.error(String(error)); }
    finally { setBusy(false); }
  };

  const restart = async (force = false) => {
    if (busy && !force) return;
    setBusy(true);
    setRestartStage("stopping");
    setRestartMessage("");
    try {
      await api.restartCodex();
      feedback.success("Codex 已重启");
      await onRefresh();
    } catch (error) {
      setRestartStage("error");
      setRestartMessage(String(error));
      feedback.error(String(error));
    } finally { setBusy(false); }
  };

  const applyProfile = async (profile: ProfileSummary) => {
    if (busy) return;
    setBusy(true);
    try {
      await api.applyProfile(profile.id);
      feedback.success("模型配置已应用");
      if (state.settings.auto_restart) await restart(true);
      await onRefresh();
    } catch (error) { feedback.error(String(error)); }
    finally { setBusy(false); }
  };

  const removeProfile = async (profile: ProfileSummary) => {
    const confirmed = await feedback.confirm({ title: "删除供应商", description: <>确定删除“<strong>{profile.name}</strong>”吗？删除后不可恢复。</>, confirmText: "删除", destructive: true });
    if (!confirmed) return;
    const previousIndex = items.findIndex((item) => item.id === profile.id);
    setItems((current) => current.filter((item) => item.id !== profile.id));
    try {
      await api.deleteProfile(profile.id);
      feedback.success("供应商已删除");
      await onRefresh();
    } catch (error) {
      setItems((current) => {
        if (current.some((item) => item.id === profile.id)) return current;
        const index = Math.max(0, Math.min(previousIndex, current.length));
        return [...current.slice(0, index), profile, ...current.slice(index)];
      });
      feedback.error(String(error));
    }
  };

  const duplicateProfile = async (profile: ProfileSummary) => {
    if (busy || duplicatingProfileRef.current) return;
    duplicatingProfileRef.current = true;
    try { const copy = await api.duplicateProfile(profile.id); feedback.success(`已复制为「${copy.name}」`); await onRefresh(); }
    catch (error) { feedback.error(String(error)); }
    finally { duplicatingProfileRef.current = false; }
  };

  const closeEdit = async () => { setEditingProfile(null); setCreatingProfile(false); await onRefresh(); };
  const boundAccountLogin = (profile: ProfileSummary) => authStatus.accounts.find((account) => account.id === profile.account_id)?.login ?? null;
  const subscriptionAccount = authStatus.external?.login ?? authStatus.accounts[0]?.login ?? null;
  const subscriptionSource = authStatus.external ? "desktop" : authStatus.accounts.length ? "oauth" : null;
  const draggedProfile = draggedProfileId ? items.find((profile) => profile.id === draggedProfileId) ?? null : null;

  if (editingProfile || creatingProfile) {
    return <ProfileEdit profile={editingProfile} create={creatingProfile} onBack={() => void closeEdit()} onChanged={() => void onRefresh()} />;
  }

  return (
    <section className="apple-scroll-page mx-auto w-full max-w-none">
      <header className="apple-page-bar flex-wrap justify-between gap-4">
        <div className="flex min-w-0 flex-wrap items-center gap-x-4 gap-y-2 text-sm"><span className={`inline-flex items-center gap-1.5 rounded-full border px-2.5 py-1 text-xs font-medium ${state.codex.running ? "border-success/25 bg-success/10 text-[var(--success-text)] dark:border-success/30 dark:bg-success/10" : "border-[var(--panel-border)] bg-black/4 muted dark:bg-white/6"}`}><span className="relative flex h-2 w-2"><span className={`relative inline-flex h-2 w-2 rounded-full ${state.codex.running ? "bg-success shadow-[0_0_6px_1px_rgba(52,199,89,0.45)]" : "bg-black/40 dark:bg-white/40"}`} /></span>Codex {state.codex.running ? "运行中" : "未运行"}</span></div>
        <div className="flex flex-wrap items-center gap-2">
          <div className="apple-toolbar-group">
            <button type="button" className="apple-action-button apple-action-button--quaternary"
              disabled={busy || (restartStage !== "idle" && restartStage !== "success" && restartStage !== "error")}
              title="重启 Codex" onClick={() => void restart(false)}>
              <RefreshCw className="h-4 w-4" strokeWidth={2} />重启 Codex
            </button>
            <button type="button" className="apple-icon-button text-accent" disabled={busy}
              title="捕获当前配置" aria-label="捕获当前配置" onClick={openCapture}>
              <Camera className="h-4 w-4" strokeWidth={2} />
            </button>
          </div>
          <button type="button" className="apple-action-button app-button--primary" disabled={busy}
            onClick={() => setCreatingProfile(true)}>
            <Plus className="h-4 w-4" strokeWidth={2} />添加供应商
          </button>
        </div>
      </header>
      <div className="apple-edit-content">
        {restartCardMounted ? <RestartProgressCard stage={restartCardStage} message={restartMessage} visible={restartCardVisible} onHidden={onRestartCardHidden} /> : null}
        <div>{items.length === 0 ? <EmptyStateCard icon={<Server className="h-5 w-5" strokeWidth={1.8} />}><p className="muted">还没有供应商配置。可以添加内置官方供应商，或先把 ~/.codex/config.toml 调整到目标状态，再点击“捕获当前配置”。</p></EmptyStateCard> : <DndContext sensors={sensors} collisionDetection={closestCenter} onDragStart={onDragStart} onDragCancel={onDragCancel} onDragEnd={onDragEnd}><SortableContext items={items.map((item) => item.id)} strategy={verticalListSortingStrategy}><div className="profile-list relative space-y-[var(--gap-page)] will-change-transform">{items.map((profile) => <ProfileCard key={profile.id} profile={profile} active={profile.id === state.active_profile_id} busy={busy} activationEpoch={activationEpoch} subscriptionAuthed={authStatus.authenticated} subscriptionAccount={subscriptionAccount} subscriptionSource={subscriptionSource} boundAccount={boundAccountLogin(profile)} balanceCache={state.balance_cache} onApply={() => void applyProfile(profile)} onRename={() => openRename(profile)} onEdit={() => setEditingProfile(profile)} onRemove={() => void removeProfile(profile)} onDuplicate={() => void duplicateProfile(profile)} />)}</div></SortableContext><DragOverlay dropAnimation={null}>{draggedProfile ? <ProfileDragPreview profile={draggedProfile} width={draggedProfileWidth} /> : null}</DragOverlay></DndContext>}</div>
      </div>
      <AppDialog open={modal !== null} onOpenChange={(open) => { if (!open) setModal(null); }} title={modal === "capture" ? "保存当前配置快照" : "重命名供应商"} initialFocusRef={nameInput} footer={<><button type="button" className="apple-action-button" onClick={() => setModal(null)}>取消</button><button type="button" className="apple-action-button app-button--primary" disabled={busy || !profileName.trim()} onClick={() => void submitModal()}>保存</button></>}>
        <div className="space-y-4"><p className="muted text-sm">{modal === "capture" ? "为当前 Codex 配置创建快照，切换供应商后可一键恢复。" : "输入新的供应商名称。"}</p><input ref={nameInput} className="app-input" maxLength={50} placeholder="例如：DeepSeek 日常" value={profileName} onChange={(event) => setProfileName(event.target.value)} onKeyDown={(event) => { if (event.key === "Enter" && !event.nativeEvent.isComposing) void submitModal(); }} /></div>
      </AppDialog>
    </section>
  );
}
